/*
    MSBuildParseEngine.cpp
    
MIT License

Copyright (c) 2016 cbtek

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
//----------------------------------------
//MSBuildParseEngine.cpp generated by cberry on 11-17-2016 at 10:40:09 PM
//----------------------------------------
#include "MSBuildParseEngine.h"

#include "utility/inc/FileUtils.hpp"
#include "utility/inc/StringUtils.hpp"

using namespace cbtek::common::utility;

namespace cbtek {
namespace common {
namespace dante {
namespace platform {
namespace msbuild {


MSBuildParseEngine::MSBuildParseEngine()
{

}

std::string MSBuildParseEngine::getId() const
{
    return "MSBuildbuild";
}

void MSBuildParseEngine::parse(const std::string & topLevelSolutionFile)
{
    std::string slnData = FileUtils::getFileContents(topLevelSolutionFile);

    std::vector<std::string> lines = StringUtils::split(slnData,"\n");

    for (const auto & line : lines)
    {
        std::string trimmedLine = StringUtils::trimmed(line);
        if (StringUtils::startsWith(trimmedLine,"Project",false))
        {
            std::string data = StringUtils::textAfter(line,"=");
            std::vector<std::string> dataItems = StringUtils::split(data,",");
            for (const auto & item : dataItems)
            {
                std::string field = StringUtils::remove(item,"\"");
                std::cerr << field<<std::endl;
            }
            std::cout << std::endl;
        }
    }

}

std::vector<ParseNode> MSBuildParseEngine::getParseNodes() const
{

}

MSBuildParseEngine::~MSBuildParseEngine()
{

}




}}}}}//end namespace


